### PR TITLE
Migrate to RTIC v2, async version

### PR DESCRIPTION
**Pull request by fmckeogh**
Async `usb-pd` should be compatible with both embassy and RTIC v2. I can only test RTIC as I could not compile embassy to fit in the 16KB of flash on the ZY12PDN.

### CODE REVIEW

**Comment by bentwire** [comment]
I'll test on embassy ASAP.

Sorry I disappeared, I got Covid, only now been able to get back to any hobby stuff.

**Comment by fmckeogh** [comment]
@bentwire I'm sorry to hear that, I hope you're feeling better

**Comment by fmckeogh** [comment]
@bentwire Actually, would you be able to test the `embassy` branch? I got it working and I think you're still right about embassy being the way to go over RTIC

**Comment by bentwire** [comment]
I need to figure out how to merge my vdm changes in to the embassy branch or just make a quick test program.  

My "quick hack" has turned in to something that sends those vendor messages and now its not a straight forward merge, oops!

The code looks good to me.  Might want to change the poll fn name.  I was thinking the next step would be to make it fully interrupt driven, and I think async uses the poll name in some of its traits?  May or may not need to worry about it...  Depends on if embassy uses that name or not when you make something an InterruptExecutor...

**Comment by fmckeogh** [comment]
@bentwire Yes, very good point about true interrupt driving. The ZY12PDNs don’t support it, but FUSB302Bs do have that interrupt pin, it would be cool to expose that as an async task that self-awaits on the interrupt pin.

I’m building some new hardware with two FUSB302Bs and an F303K8, this should fix the binary size issues I’ve been having.

**Pull request closed without merging**
