### PR TITLE
Added feature gate to work with latest embassy.

### PR DESCRIPTION
**Pull request by bentwire**
Probably needs some cleanup..

### CODE REVIEW

**Comment by bentwire** [comment]
Hmm not sure why the build is failing.  I didn't set those options...

**Comment by fmckeogh** [comment]
@bentwire If embassy seems to be replacing RTIC in the ecosystem I'm more than happy to just make this an embassy-first library and if anyone needs the original time implementation they can add a compat feature, does that work for you?

**Comment by bentwire** [comment]
I'm fine with that.  Its supposed to go live (posted to crates.io) in the next week as soon as some features get in to stable compiler.

So far I like it.  Only been messing with it for a week though.

**Comment by fmckeogh** [comment]
@bentwire You're the only library user right now and the project I'm doing is easy to move to a new framework. Ideally I'd like to avoid using features for as long as possible.

**Comment by bentwire** [comment]
@fmckeogh 

Yes I agree the features make it ugly.   The one thing I like about embassy is async.  I think this lib could benefit from embassy for that reason alone.

I'm fine with doing a full async port to embassy if you are.

**Comment by bentwire** [comment]
@fmckeogh 
I could start by just moving to embassy blocking as the code works as is with it, and that is how I am using it currently.

**Comment by bentwire** [comment]
I think I need to add a rust-toolchain.toml to fox that build failure.  At least until embassy is on stable rust. 

Hopefully it won't be too much longer.  They are waiting for a couple features related to async getting in stable.

**Comment by fmckeogh** [comment]
Superseded by #10

**Pull request closed without merging**
